<header>
  <img src="/assets/images/tux_rambo.svg" alt="tux rambo" class="logo">
  <strong>beram</strong>'s blog.
  <nav>
    <ul>
      <li><a href="/about-me.html">About me</a></li>
      <li><a href="/talks-events.html">Talks</a></li>
    </ul>
  </nav>
  <div class="social">
    <a href="https://github.com/brambaud" title="Github's Profile"><img src="/assets/images/github.svg" alt="Github"></a>
    <a href="https://gitlab.com/beram" title="GitLab's Profile"><img src="/assets/images/gitlab.svg" alt="GitLab"></a>
    <a href="https://twitter.com/rambaud_b" title="Twitter's Profile"><img src="/assets/images/twitter.svg" alt="Twitter"></a>
  </div>
</header>
