<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <title><?php print $title; ?> - beram's blog</title>
  <link rel="canonical" href="https://brambaud.github.io/">
  <meta property="og:title" content="beram's blog">
  <meta name="twitter:title" content="beram's blog">
  <?php print \part('favicon'); ?>
  <link rel="stylesheet" href="/assets/css/reset.css">
  <link rel="stylesheet" href="/assets/css/main.css">
</head>
<body>
<?php print \part('header'); ?>
<main>
  <?php print $content; ?>
</main>
</body>
</html>
