<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <title><?php print $title; ?> - beram's blog</title>
  <link rel="canonical" href="https://brambaud.github.io/">
  <meta property="og:title" content="beram's blog">
  <meta name="twitter:title" content="beram's blog">
  <?php print \part('favicon'); ?>
  <link rel="stylesheet" href="/assets/css/reset.css">
  <link rel="stylesheet" href="/assets/css/main.css">
  <link rel="stylesheet" href="/assets/css/mobile.css">
</head>
<body>
<?php print \part('header'); ?>
<main>
  <div class="posts">
    <?php foreach(\posts_from_sources($site->sources) as $post): ?>
    <div class="post">
      <h2 class="post-title">
        <a href="<?php print $post->relativeUrl; ?>"><?php print $post->document->metadata->getProperty('title')->value; ?></a>
      </h2>
      <time datetime="<?php print $post->document->metadata->getProperty('date')->value; ?>" class="post-meta"><?php print $post->document->metadata->getProperty('date')->value; ?></time>
      <p class="post-excerpt">
        <?php print $post->document->metadata->getProperty('excerpt')->value; ?>
      </p>
    </div>
    <?php endforeach ?>
  </div>
</main>
</body>
</html>
